name: Check
on:
  push
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Check scalafmtCheck
        run: sbt scalafmtCheckAll Test/scalafmtCheckAll scalafmtSbtCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Tests
        run: sbt clean coverage +test; sbt coverageReport
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: scoverage-report
          path: target/scala-3.2.2/scoverage-report
